version: "3.0"
services:
    rasa:
      container_name: rasa
      image: rasa/rasa
      ports:
        - 5005:5005
      volumes:
        - ./:/app
      command:
        -  train 
      depends_on:
        - db
            
    db: 
      image: "postgres"
      environment:
        POSTGRESQL_USERNAME: "postgres"
        POSTGRESQL_PASSWORD: "password"
        POSTGRESQL_DATABASE: "postgres"
        POSTGRES_HOST_AUTH_METHOD: "trust"
      volumes:
        - ./database/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      ports:
        - "5432:5432"
      networks:
        - default